version: 2.0
jobs:
  unit:
    docker:
      - image: circleci/node:8
    steps:
      - run: node --version
      - run: yarn --version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: npm run test
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test-and-release:
    jobs:
      - unit
      - release:
          requires:
            - unit
